#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEntity
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DNATraining")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGrade(Grade instance);
    partial void UpdateGrade(Grade instance);
    partial void DeleteGrade(Grade instance);
    partial void InsertGradeGroup(GradeGroup instance);
    partial void UpdateGradeGroup(GradeGroup instance);
    partial void DeleteGradeGroup(GradeGroup instance);
    partial void InsertGradeSalary(GradeSalary instance);
    partial void UpdateGradeSalary(GradeSalary instance);
    partial void DeleteGradeSalary(GradeSalary instance);
    partial void InsertGradeZone(GradeZone instance);
    partial void UpdateGradeZone(GradeZone instance);
    partial void DeleteGradeZone(GradeZone instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DNATrainingConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Grade> Grades
		{
			get
			{
				return this.GetTable<Grade>();
			}
		}
		
		public System.Data.Linq.Table<GradeGroup> GradeGroups
		{
			get
			{
				return this.GetTable<GradeGroup>();
			}
		}
		
		public System.Data.Linq.Table<GradeSalary> GradeSalaries
		{
			get
			{
				return this.GetTable<GradeSalary>();
			}
		}
		
		public System.Data.Linq.Table<GradeZone> GradeZones
		{
			get
			{
				return this.GetTable<GradeZone>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Grades")]
	public partial class Grade : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _Grade1;
		
		private string _GradeName;
		
		private string _GradeAName;
		
		private string _GradeFName;
		
		private short _GradeYears;
		
		private decimal _GradeStepAmount;
		
		private short _GradeOrder;
		
		private System.Nullable<short> _GradeGroup;
		
		private short _bcount;
		
		private decimal _bsalary;
		
		private short _level_priv;
		
		private int _GradeCons;
		
		private string _GradeNameCons;
		
		private string _GradeANameCons;
		
		private string _GradeFNameCons;
		
		private System.Nullable<System.DateTime> _GradeFromDate;
		
		private System.Nullable<System.DateTime> _GradeToDate;
		
		private string _GradesRoles;
		
		private short _GradesRYear;
		
		private string _GradesRNo;
		
		private System.Nullable<System.DateTime> _GradesRIssueDate;
		
		private System.Nullable<System.DateTime> _GradesRExecDate;
		
		private System.Nullable<short> _GradesRStatus;
		
		private System.Nullable<short> _GradesRSource;
		
		private string _GradesRDesc;
		
		private System.Guid _GradesGUID;
		
		private EntitySet<GradeSalary> _GradeSalaries;
		
		private EntitySet<GradeZone> _GradeZones;
		
		private EntityRef<GradeGroup> _GradeGroup1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGrade1Changing(short value);
    partial void OnGrade1Changed();
    partial void OnGradeNameChanging(string value);
    partial void OnGradeNameChanged();
    partial void OnGradeANameChanging(string value);
    partial void OnGradeANameChanged();
    partial void OnGradeFNameChanging(string value);
    partial void OnGradeFNameChanged();
    partial void OnGradeYearsChanging(short value);
    partial void OnGradeYearsChanged();
    partial void OnGradeStepAmountChanging(decimal value);
    partial void OnGradeStepAmountChanged();
    partial void OnGradeOrderChanging(short value);
    partial void OnGradeOrderChanged();
    partial void OnGradeGroupChanging(System.Nullable<short> value);
    partial void OnGradeGroupChanged();
    partial void OnbcountChanging(short value);
    partial void OnbcountChanged();
    partial void OnbsalaryChanging(decimal value);
    partial void OnbsalaryChanged();
    partial void Onlevel_privChanging(short value);
    partial void Onlevel_privChanged();
    partial void OnGradeConsChanging(int value);
    partial void OnGradeConsChanged();
    partial void OnGradeNameConsChanging(string value);
    partial void OnGradeNameConsChanged();
    partial void OnGradeANameConsChanging(string value);
    partial void OnGradeANameConsChanged();
    partial void OnGradeFNameConsChanging(string value);
    partial void OnGradeFNameConsChanged();
    partial void OnGradeFromDateChanging(System.Nullable<System.DateTime> value);
    partial void OnGradeFromDateChanged();
    partial void OnGradeToDateChanging(System.Nullable<System.DateTime> value);
    partial void OnGradeToDateChanged();
    partial void OnGradesRolesChanging(string value);
    partial void OnGradesRolesChanged();
    partial void OnGradesRYearChanging(short value);
    partial void OnGradesRYearChanged();
    partial void OnGradesRNoChanging(string value);
    partial void OnGradesRNoChanged();
    partial void OnGradesRIssueDateChanging(System.Nullable<System.DateTime> value);
    partial void OnGradesRIssueDateChanged();
    partial void OnGradesRExecDateChanging(System.Nullable<System.DateTime> value);
    partial void OnGradesRExecDateChanged();
    partial void OnGradesRStatusChanging(System.Nullable<short> value);
    partial void OnGradesRStatusChanged();
    partial void OnGradesRSourceChanging(System.Nullable<short> value);
    partial void OnGradesRSourceChanged();
    partial void OnGradesRDescChanging(string value);
    partial void OnGradesRDescChanged();
    partial void OnGradesGUIDChanging(System.Guid value);
    partial void OnGradesGUIDChanged();
    #endregion
		
		public Grade()
		{
			this._GradeSalaries = new EntitySet<GradeSalary>(new Action<GradeSalary>(this.attach_GradeSalaries), new Action<GradeSalary>(this.detach_GradeSalaries));
			this._GradeZones = new EntitySet<GradeZone>(new Action<GradeZone>(this.attach_GradeZones), new Action<GradeZone>(this.detach_GradeZones));
			this._GradeGroup1 = default(EntityRef<GradeGroup>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Grade", Storage="_Grade1", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short Grade1
		{
			get
			{
				return this._Grade1;
			}
			set
			{
				if ((this._Grade1 != value))
				{
					this.OnGrade1Changing(value);
					this.SendPropertyChanging();
					this._Grade1 = value;
					this.SendPropertyChanged("Grade1");
					this.OnGrade1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeName", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string GradeName
		{
			get
			{
				return this._GradeName;
			}
			set
			{
				if ((this._GradeName != value))
				{
					this.OnGradeNameChanging(value);
					this.SendPropertyChanging();
					this._GradeName = value;
					this.SendPropertyChanged("GradeName");
					this.OnGradeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeAName", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string GradeAName
		{
			get
			{
				return this._GradeAName;
			}
			set
			{
				if ((this._GradeAName != value))
				{
					this.OnGradeANameChanging(value);
					this.SendPropertyChanging();
					this._GradeAName = value;
					this.SendPropertyChanged("GradeAName");
					this.OnGradeANameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeFName", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string GradeFName
		{
			get
			{
				return this._GradeFName;
			}
			set
			{
				if ((this._GradeFName != value))
				{
					this.OnGradeFNameChanging(value);
					this.SendPropertyChanging();
					this._GradeFName = value;
					this.SendPropertyChanged("GradeFName");
					this.OnGradeFNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeYears", DbType="SmallInt NOT NULL")]
		public short GradeYears
		{
			get
			{
				return this._GradeYears;
			}
			set
			{
				if ((this._GradeYears != value))
				{
					this.OnGradeYearsChanging(value);
					this.SendPropertyChanging();
					this._GradeYears = value;
					this.SendPropertyChanged("GradeYears");
					this.OnGradeYearsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeStepAmount", DbType="Decimal(18,3) NOT NULL")]
		public decimal GradeStepAmount
		{
			get
			{
				return this._GradeStepAmount;
			}
			set
			{
				if ((this._GradeStepAmount != value))
				{
					this.OnGradeStepAmountChanging(value);
					this.SendPropertyChanging();
					this._GradeStepAmount = value;
					this.SendPropertyChanged("GradeStepAmount");
					this.OnGradeStepAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeOrder", DbType="SmallInt NOT NULL")]
		public short GradeOrder
		{
			get
			{
				return this._GradeOrder;
			}
			set
			{
				if ((this._GradeOrder != value))
				{
					this.OnGradeOrderChanging(value);
					this.SendPropertyChanging();
					this._GradeOrder = value;
					this.SendPropertyChanged("GradeOrder");
					this.OnGradeOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeGroup", DbType="SmallInt")]
		public System.Nullable<short> GradeGroup
		{
			get
			{
				return this._GradeGroup;
			}
			set
			{
				if ((this._GradeGroup != value))
				{
					if (this._GradeGroup1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGradeGroupChanging(value);
					this.SendPropertyChanging();
					this._GradeGroup = value;
					this.SendPropertyChanged("GradeGroup");
					this.OnGradeGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bcount", DbType="SmallInt NOT NULL")]
		public short bcount
		{
			get
			{
				return this._bcount;
			}
			set
			{
				if ((this._bcount != value))
				{
					this.OnbcountChanging(value);
					this.SendPropertyChanging();
					this._bcount = value;
					this.SendPropertyChanged("bcount");
					this.OnbcountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bsalary", DbType="Decimal(18,3) NOT NULL")]
		public decimal bsalary
		{
			get
			{
				return this._bsalary;
			}
			set
			{
				if ((this._bsalary != value))
				{
					this.OnbsalaryChanging(value);
					this.SendPropertyChanging();
					this._bsalary = value;
					this.SendPropertyChanged("bsalary");
					this.OnbsalaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_level_priv", DbType="SmallInt NOT NULL")]
		public short level_priv
		{
			get
			{
				return this._level_priv;
			}
			set
			{
				if ((this._level_priv != value))
				{
					this.Onlevel_privChanging(value);
					this.SendPropertyChanging();
					this._level_priv = value;
					this.SendPropertyChanged("level_priv");
					this.Onlevel_privChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeCons", DbType="Int NOT NULL")]
		public int GradeCons
		{
			get
			{
				return this._GradeCons;
			}
			set
			{
				if ((this._GradeCons != value))
				{
					this.OnGradeConsChanging(value);
					this.SendPropertyChanging();
					this._GradeCons = value;
					this.SendPropertyChanged("GradeCons");
					this.OnGradeConsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeNameCons", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string GradeNameCons
		{
			get
			{
				return this._GradeNameCons;
			}
			set
			{
				if ((this._GradeNameCons != value))
				{
					this.OnGradeNameConsChanging(value);
					this.SendPropertyChanging();
					this._GradeNameCons = value;
					this.SendPropertyChanged("GradeNameCons");
					this.OnGradeNameConsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeANameCons", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string GradeANameCons
		{
			get
			{
				return this._GradeANameCons;
			}
			set
			{
				if ((this._GradeANameCons != value))
				{
					this.OnGradeANameConsChanging(value);
					this.SendPropertyChanging();
					this._GradeANameCons = value;
					this.SendPropertyChanged("GradeANameCons");
					this.OnGradeANameConsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeFNameCons", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string GradeFNameCons
		{
			get
			{
				return this._GradeFNameCons;
			}
			set
			{
				if ((this._GradeFNameCons != value))
				{
					this.OnGradeFNameConsChanging(value);
					this.SendPropertyChanging();
					this._GradeFNameCons = value;
					this.SendPropertyChanged("GradeFNameCons");
					this.OnGradeFNameConsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeFromDate", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> GradeFromDate
		{
			get
			{
				return this._GradeFromDate;
			}
			set
			{
				if ((this._GradeFromDate != value))
				{
					this.OnGradeFromDateChanging(value);
					this.SendPropertyChanging();
					this._GradeFromDate = value;
					this.SendPropertyChanged("GradeFromDate");
					this.OnGradeFromDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeToDate", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> GradeToDate
		{
			get
			{
				return this._GradeToDate;
			}
			set
			{
				if ((this._GradeToDate != value))
				{
					this.OnGradeToDateChanging(value);
					this.SendPropertyChanging();
					this._GradeToDate = value;
					this.SendPropertyChanged("GradeToDate");
					this.OnGradeToDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradesRoles", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string GradesRoles
		{
			get
			{
				return this._GradesRoles;
			}
			set
			{
				if ((this._GradesRoles != value))
				{
					this.OnGradesRolesChanging(value);
					this.SendPropertyChanging();
					this._GradesRoles = value;
					this.SendPropertyChanged("GradesRoles");
					this.OnGradesRolesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradesRYear", DbType="SmallInt NOT NULL")]
		public short GradesRYear
		{
			get
			{
				return this._GradesRYear;
			}
			set
			{
				if ((this._GradesRYear != value))
				{
					this.OnGradesRYearChanging(value);
					this.SendPropertyChanging();
					this._GradesRYear = value;
					this.SendPropertyChanged("GradesRYear");
					this.OnGradesRYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradesRNo", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string GradesRNo
		{
			get
			{
				return this._GradesRNo;
			}
			set
			{
				if ((this._GradesRNo != value))
				{
					this.OnGradesRNoChanging(value);
					this.SendPropertyChanging();
					this._GradesRNo = value;
					this.SendPropertyChanged("GradesRNo");
					this.OnGradesRNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradesRIssueDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> GradesRIssueDate
		{
			get
			{
				return this._GradesRIssueDate;
			}
			set
			{
				if ((this._GradesRIssueDate != value))
				{
					this.OnGradesRIssueDateChanging(value);
					this.SendPropertyChanging();
					this._GradesRIssueDate = value;
					this.SendPropertyChanged("GradesRIssueDate");
					this.OnGradesRIssueDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradesRExecDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> GradesRExecDate
		{
			get
			{
				return this._GradesRExecDate;
			}
			set
			{
				if ((this._GradesRExecDate != value))
				{
					this.OnGradesRExecDateChanging(value);
					this.SendPropertyChanging();
					this._GradesRExecDate = value;
					this.SendPropertyChanged("GradesRExecDate");
					this.OnGradesRExecDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradesRStatus", DbType="SmallInt")]
		public System.Nullable<short> GradesRStatus
		{
			get
			{
				return this._GradesRStatus;
			}
			set
			{
				if ((this._GradesRStatus != value))
				{
					this.OnGradesRStatusChanging(value);
					this.SendPropertyChanging();
					this._GradesRStatus = value;
					this.SendPropertyChanged("GradesRStatus");
					this.OnGradesRStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradesRSource", DbType="SmallInt")]
		public System.Nullable<short> GradesRSource
		{
			get
			{
				return this._GradesRSource;
			}
			set
			{
				if ((this._GradesRSource != value))
				{
					this.OnGradesRSourceChanging(value);
					this.SendPropertyChanging();
					this._GradesRSource = value;
					this.SendPropertyChanged("GradesRSource");
					this.OnGradesRSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradesRDesc", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string GradesRDesc
		{
			get
			{
				return this._GradesRDesc;
			}
			set
			{
				if ((this._GradesRDesc != value))
				{
					this.OnGradesRDescChanging(value);
					this.SendPropertyChanging();
					this._GradesRDesc = value;
					this.SendPropertyChanged("GradesRDesc");
					this.OnGradesRDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradesGUID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GradesGUID
		{
			get
			{
				return this._GradesGUID;
			}
			set
			{
				if ((this._GradesGUID != value))
				{
					this.OnGradesGUIDChanging(value);
					this.SendPropertyChanging();
					this._GradesGUID = value;
					this.SendPropertyChanged("GradesGUID");
					this.OnGradesGUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Grade_GradeSalary", Storage="_GradeSalaries", ThisKey="Grade1", OtherKey="Grade")]
		public EntitySet<GradeSalary> GradeSalaries
		{
			get
			{
				return this._GradeSalaries;
			}
			set
			{
				this._GradeSalaries.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Grade_GradeZone", Storage="_GradeZones", ThisKey="Grade1", OtherKey="Grade")]
		public EntitySet<GradeZone> GradeZones
		{
			get
			{
				return this._GradeZones;
			}
			set
			{
				this._GradeZones.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GradeGroup_Grade", Storage="_GradeGroup1", ThisKey="GradeGroup", OtherKey="GradeGroup1", IsForeignKey=true)]
		public GradeGroup GradeGroup1
		{
			get
			{
				return this._GradeGroup1.Entity;
			}
			set
			{
				GradeGroup previousValue = this._GradeGroup1.Entity;
				if (((previousValue != value) 
							|| (this._GradeGroup1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GradeGroup1.Entity = null;
						previousValue.Grades.Remove(this);
					}
					this._GradeGroup1.Entity = value;
					if ((value != null))
					{
						value.Grades.Add(this);
						this._GradeGroup = value.GradeGroup1;
					}
					else
					{
						this._GradeGroup = default(Nullable<short>);
					}
					this.SendPropertyChanged("GradeGroup1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GradeSalaries(GradeSalary entity)
		{
			this.SendPropertyChanging();
			entity.Grade1 = this;
		}
		
		private void detach_GradeSalaries(GradeSalary entity)
		{
			this.SendPropertyChanging();
			entity.Grade1 = null;
		}
		
		private void attach_GradeZones(GradeZone entity)
		{
			this.SendPropertyChanging();
			entity.Grade1 = this;
		}
		
		private void detach_GradeZones(GradeZone entity)
		{
			this.SendPropertyChanging();
			entity.Grade1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GradeGroups")]
	public partial class GradeGroup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _GradeGroup1;
		
		private string _GradeGroupName;
		
		private string _GradeGroupAName;
		
		private string _GradeGroupFName;
		
		private short _GradeGroupOrder;
		
		private int _GradeGroupCons;
		
		private string _GradeGroupNameCons;
		
		private string _GradeGroupANameCons;
		
		private string _GradeGroupFNameCons;
		
		private System.Nullable<System.DateTime> _GradeGroupFromDate;
		
		private System.Nullable<System.DateTime> _GradeGroupToDate;
		
		private string _GradeGroupsRoles;
		
		private short _GradeGroupsRYear;
		
		private string _GradeGroupsRNo;
		
		private System.Nullable<System.DateTime> _GradeGroupsRIssueDate;
		
		private System.Nullable<System.DateTime> _GradeGroupsRExecDate;
		
		private System.Nullable<short> _GradeGroupsRStatus;
		
		private System.Nullable<short> _GradeGroupsRSource;
		
		private string _GradeGroupsRDesc;
		
		private System.Guid _GradeGroupsGUID;
		
		private EntitySet<Grade> _Grades;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGradeGroup1Changing(short value);
    partial void OnGradeGroup1Changed();
    partial void OnGradeGroupNameChanging(string value);
    partial void OnGradeGroupNameChanged();
    partial void OnGradeGroupANameChanging(string value);
    partial void OnGradeGroupANameChanged();
    partial void OnGradeGroupFNameChanging(string value);
    partial void OnGradeGroupFNameChanged();
    partial void OnGradeGroupOrderChanging(short value);
    partial void OnGradeGroupOrderChanged();
    partial void OnGradeGroupConsChanging(int value);
    partial void OnGradeGroupConsChanged();
    partial void OnGradeGroupNameConsChanging(string value);
    partial void OnGradeGroupNameConsChanged();
    partial void OnGradeGroupANameConsChanging(string value);
    partial void OnGradeGroupANameConsChanged();
    partial void OnGradeGroupFNameConsChanging(string value);
    partial void OnGradeGroupFNameConsChanged();
    partial void OnGradeGroupFromDateChanging(System.Nullable<System.DateTime> value);
    partial void OnGradeGroupFromDateChanged();
    partial void OnGradeGroupToDateChanging(System.Nullable<System.DateTime> value);
    partial void OnGradeGroupToDateChanged();
    partial void OnGradeGroupsRolesChanging(string value);
    partial void OnGradeGroupsRolesChanged();
    partial void OnGradeGroupsRYearChanging(short value);
    partial void OnGradeGroupsRYearChanged();
    partial void OnGradeGroupsRNoChanging(string value);
    partial void OnGradeGroupsRNoChanged();
    partial void OnGradeGroupsRIssueDateChanging(System.Nullable<System.DateTime> value);
    partial void OnGradeGroupsRIssueDateChanged();
    partial void OnGradeGroupsRExecDateChanging(System.Nullable<System.DateTime> value);
    partial void OnGradeGroupsRExecDateChanged();
    partial void OnGradeGroupsRStatusChanging(System.Nullable<short> value);
    partial void OnGradeGroupsRStatusChanged();
    partial void OnGradeGroupsRSourceChanging(System.Nullable<short> value);
    partial void OnGradeGroupsRSourceChanged();
    partial void OnGradeGroupsRDescChanging(string value);
    partial void OnGradeGroupsRDescChanged();
    partial void OnGradeGroupsGUIDChanging(System.Guid value);
    partial void OnGradeGroupsGUIDChanged();
    #endregion
		
		public GradeGroup()
		{
			this._Grades = new EntitySet<Grade>(new Action<Grade>(this.attach_Grades), new Action<Grade>(this.detach_Grades));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="GradeGroup", Storage="_GradeGroup1", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short GradeGroup1
		{
			get
			{
				return this._GradeGroup1;
			}
			set
			{
				if ((this._GradeGroup1 != value))
				{
					this.OnGradeGroup1Changing(value);
					this.SendPropertyChanging();
					this._GradeGroup1 = value;
					this.SendPropertyChanged("GradeGroup1");
					this.OnGradeGroup1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeGroupName", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string GradeGroupName
		{
			get
			{
				return this._GradeGroupName;
			}
			set
			{
				if ((this._GradeGroupName != value))
				{
					this.OnGradeGroupNameChanging(value);
					this.SendPropertyChanging();
					this._GradeGroupName = value;
					this.SendPropertyChanged("GradeGroupName");
					this.OnGradeGroupNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeGroupAName", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string GradeGroupAName
		{
			get
			{
				return this._GradeGroupAName;
			}
			set
			{
				if ((this._GradeGroupAName != value))
				{
					this.OnGradeGroupANameChanging(value);
					this.SendPropertyChanging();
					this._GradeGroupAName = value;
					this.SendPropertyChanged("GradeGroupAName");
					this.OnGradeGroupANameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeGroupFName", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string GradeGroupFName
		{
			get
			{
				return this._GradeGroupFName;
			}
			set
			{
				if ((this._GradeGroupFName != value))
				{
					this.OnGradeGroupFNameChanging(value);
					this.SendPropertyChanging();
					this._GradeGroupFName = value;
					this.SendPropertyChanged("GradeGroupFName");
					this.OnGradeGroupFNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeGroupOrder", DbType="SmallInt NOT NULL")]
		public short GradeGroupOrder
		{
			get
			{
				return this._GradeGroupOrder;
			}
			set
			{
				if ((this._GradeGroupOrder != value))
				{
					this.OnGradeGroupOrderChanging(value);
					this.SendPropertyChanging();
					this._GradeGroupOrder = value;
					this.SendPropertyChanged("GradeGroupOrder");
					this.OnGradeGroupOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeGroupCons", DbType="Int NOT NULL")]
		public int GradeGroupCons
		{
			get
			{
				return this._GradeGroupCons;
			}
			set
			{
				if ((this._GradeGroupCons != value))
				{
					this.OnGradeGroupConsChanging(value);
					this.SendPropertyChanging();
					this._GradeGroupCons = value;
					this.SendPropertyChanged("GradeGroupCons");
					this.OnGradeGroupConsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeGroupNameCons", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string GradeGroupNameCons
		{
			get
			{
				return this._GradeGroupNameCons;
			}
			set
			{
				if ((this._GradeGroupNameCons != value))
				{
					this.OnGradeGroupNameConsChanging(value);
					this.SendPropertyChanging();
					this._GradeGroupNameCons = value;
					this.SendPropertyChanged("GradeGroupNameCons");
					this.OnGradeGroupNameConsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeGroupANameCons", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string GradeGroupANameCons
		{
			get
			{
				return this._GradeGroupANameCons;
			}
			set
			{
				if ((this._GradeGroupANameCons != value))
				{
					this.OnGradeGroupANameConsChanging(value);
					this.SendPropertyChanging();
					this._GradeGroupANameCons = value;
					this.SendPropertyChanged("GradeGroupANameCons");
					this.OnGradeGroupANameConsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeGroupFNameCons", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string GradeGroupFNameCons
		{
			get
			{
				return this._GradeGroupFNameCons;
			}
			set
			{
				if ((this._GradeGroupFNameCons != value))
				{
					this.OnGradeGroupFNameConsChanging(value);
					this.SendPropertyChanging();
					this._GradeGroupFNameCons = value;
					this.SendPropertyChanged("GradeGroupFNameCons");
					this.OnGradeGroupFNameConsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeGroupFromDate", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> GradeGroupFromDate
		{
			get
			{
				return this._GradeGroupFromDate;
			}
			set
			{
				if ((this._GradeGroupFromDate != value))
				{
					this.OnGradeGroupFromDateChanging(value);
					this.SendPropertyChanging();
					this._GradeGroupFromDate = value;
					this.SendPropertyChanged("GradeGroupFromDate");
					this.OnGradeGroupFromDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeGroupToDate", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> GradeGroupToDate
		{
			get
			{
				return this._GradeGroupToDate;
			}
			set
			{
				if ((this._GradeGroupToDate != value))
				{
					this.OnGradeGroupToDateChanging(value);
					this.SendPropertyChanging();
					this._GradeGroupToDate = value;
					this.SendPropertyChanged("GradeGroupToDate");
					this.OnGradeGroupToDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeGroupsRoles", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string GradeGroupsRoles
		{
			get
			{
				return this._GradeGroupsRoles;
			}
			set
			{
				if ((this._GradeGroupsRoles != value))
				{
					this.OnGradeGroupsRolesChanging(value);
					this.SendPropertyChanging();
					this._GradeGroupsRoles = value;
					this.SendPropertyChanged("GradeGroupsRoles");
					this.OnGradeGroupsRolesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeGroupsRYear", DbType="SmallInt NOT NULL")]
		public short GradeGroupsRYear
		{
			get
			{
				return this._GradeGroupsRYear;
			}
			set
			{
				if ((this._GradeGroupsRYear != value))
				{
					this.OnGradeGroupsRYearChanging(value);
					this.SendPropertyChanging();
					this._GradeGroupsRYear = value;
					this.SendPropertyChanged("GradeGroupsRYear");
					this.OnGradeGroupsRYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeGroupsRNo", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string GradeGroupsRNo
		{
			get
			{
				return this._GradeGroupsRNo;
			}
			set
			{
				if ((this._GradeGroupsRNo != value))
				{
					this.OnGradeGroupsRNoChanging(value);
					this.SendPropertyChanging();
					this._GradeGroupsRNo = value;
					this.SendPropertyChanged("GradeGroupsRNo");
					this.OnGradeGroupsRNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeGroupsRIssueDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> GradeGroupsRIssueDate
		{
			get
			{
				return this._GradeGroupsRIssueDate;
			}
			set
			{
				if ((this._GradeGroupsRIssueDate != value))
				{
					this.OnGradeGroupsRIssueDateChanging(value);
					this.SendPropertyChanging();
					this._GradeGroupsRIssueDate = value;
					this.SendPropertyChanged("GradeGroupsRIssueDate");
					this.OnGradeGroupsRIssueDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeGroupsRExecDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> GradeGroupsRExecDate
		{
			get
			{
				return this._GradeGroupsRExecDate;
			}
			set
			{
				if ((this._GradeGroupsRExecDate != value))
				{
					this.OnGradeGroupsRExecDateChanging(value);
					this.SendPropertyChanging();
					this._GradeGroupsRExecDate = value;
					this.SendPropertyChanged("GradeGroupsRExecDate");
					this.OnGradeGroupsRExecDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeGroupsRStatus", DbType="SmallInt")]
		public System.Nullable<short> GradeGroupsRStatus
		{
			get
			{
				return this._GradeGroupsRStatus;
			}
			set
			{
				if ((this._GradeGroupsRStatus != value))
				{
					this.OnGradeGroupsRStatusChanging(value);
					this.SendPropertyChanging();
					this._GradeGroupsRStatus = value;
					this.SendPropertyChanged("GradeGroupsRStatus");
					this.OnGradeGroupsRStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeGroupsRSource", DbType="SmallInt")]
		public System.Nullable<short> GradeGroupsRSource
		{
			get
			{
				return this._GradeGroupsRSource;
			}
			set
			{
				if ((this._GradeGroupsRSource != value))
				{
					this.OnGradeGroupsRSourceChanging(value);
					this.SendPropertyChanging();
					this._GradeGroupsRSource = value;
					this.SendPropertyChanged("GradeGroupsRSource");
					this.OnGradeGroupsRSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeGroupsRDesc", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string GradeGroupsRDesc
		{
			get
			{
				return this._GradeGroupsRDesc;
			}
			set
			{
				if ((this._GradeGroupsRDesc != value))
				{
					this.OnGradeGroupsRDescChanging(value);
					this.SendPropertyChanging();
					this._GradeGroupsRDesc = value;
					this.SendPropertyChanged("GradeGroupsRDesc");
					this.OnGradeGroupsRDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeGroupsGUID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GradeGroupsGUID
		{
			get
			{
				return this._GradeGroupsGUID;
			}
			set
			{
				if ((this._GradeGroupsGUID != value))
				{
					this.OnGradeGroupsGUIDChanging(value);
					this.SendPropertyChanging();
					this._GradeGroupsGUID = value;
					this.SendPropertyChanged("GradeGroupsGUID");
					this.OnGradeGroupsGUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GradeGroup_Grade", Storage="_Grades", ThisKey="GradeGroup1", OtherKey="GradeGroup")]
		public EntitySet<Grade> Grades
		{
			get
			{
				return this._Grades;
			}
			set
			{
				this._Grades.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Grades(Grade entity)
		{
			this.SendPropertyChanging();
			entity.GradeGroup1 = this;
		}
		
		private void detach_Grades(Grade entity)
		{
			this.SendPropertyChanging();
			entity.GradeGroup1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GradeSalary")]
	public partial class GradeSalary : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _PayrollGroup;
		
		private short _Grade;
		
		private short _Paycode;
		
		private System.DateTime _StartDate;
		
		private decimal _GradeAmount;
		
		private System.Guid _GradeSalaryGUID;
		
		private EntityRef<Grade> _Grade1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPayrollGroupChanging(short value);
    partial void OnPayrollGroupChanged();
    partial void OnGradeChanging(short value);
    partial void OnGradeChanged();
    partial void OnPaycodeChanging(short value);
    partial void OnPaycodeChanged();
    partial void OnStartDateChanging(System.DateTime value);
    partial void OnStartDateChanged();
    partial void OnGradeAmountChanging(decimal value);
    partial void OnGradeAmountChanged();
    partial void OnGradeSalaryGUIDChanging(System.Guid value);
    partial void OnGradeSalaryGUIDChanged();
    #endregion
		
		public GradeSalary()
		{
			this._Grade1 = default(EntityRef<Grade>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayrollGroup", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short PayrollGroup
		{
			get
			{
				return this._PayrollGroup;
			}
			set
			{
				if ((this._PayrollGroup != value))
				{
					this.OnPayrollGroupChanging(value);
					this.SendPropertyChanging();
					this._PayrollGroup = value;
					this.SendPropertyChanged("PayrollGroup");
					this.OnPayrollGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grade", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short Grade
		{
			get
			{
				return this._Grade;
			}
			set
			{
				if ((this._Grade != value))
				{
					if (this._Grade1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGradeChanging(value);
					this.SendPropertyChanging();
					this._Grade = value;
					this.SendPropertyChanged("Grade");
					this.OnGradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paycode", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short Paycode
		{
			get
			{
				return this._Paycode;
			}
			set
			{
				if ((this._Paycode != value))
				{
					this.OnPaycodeChanging(value);
					this.SendPropertyChanging();
					this._Paycode = value;
					this.SendPropertyChanged("Paycode");
					this.OnPaycodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="SmallDateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeAmount", DbType="Decimal(18,3) NOT NULL")]
		public decimal GradeAmount
		{
			get
			{
				return this._GradeAmount;
			}
			set
			{
				if ((this._GradeAmount != value))
				{
					this.OnGradeAmountChanging(value);
					this.SendPropertyChanging();
					this._GradeAmount = value;
					this.SendPropertyChanged("GradeAmount");
					this.OnGradeAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeSalaryGUID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GradeSalaryGUID
		{
			get
			{
				return this._GradeSalaryGUID;
			}
			set
			{
				if ((this._GradeSalaryGUID != value))
				{
					this.OnGradeSalaryGUIDChanging(value);
					this.SendPropertyChanging();
					this._GradeSalaryGUID = value;
					this.SendPropertyChanged("GradeSalaryGUID");
					this.OnGradeSalaryGUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Grade_GradeSalary", Storage="_Grade1", ThisKey="Grade", OtherKey="Grade1", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Grade Grade1
		{
			get
			{
				return this._Grade1.Entity;
			}
			set
			{
				Grade previousValue = this._Grade1.Entity;
				if (((previousValue != value) 
							|| (this._Grade1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Grade1.Entity = null;
						previousValue.GradeSalaries.Remove(this);
					}
					this._Grade1.Entity = value;
					if ((value != null))
					{
						value.GradeSalaries.Add(this);
						this._Grade = value.Grade1;
					}
					else
					{
						this._Grade = default(short);
					}
					this.SendPropertyChanged("Grade1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GradeZone")]
	public partial class GradeZone : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _Grade;
		
		private string _Zone;
		
		private short _Paycode;
		
		private System.DateTime _StartDate;
		
		private short _ZoneCurrency;
		
		private decimal _MinAmount;
		
		private decimal _MidAmount;
		
		private decimal _MaxAmount;
		
		private System.Guid _GradeZoneGUID;
		
		private EntityRef<Grade> _Grade1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGradeChanging(short value);
    partial void OnGradeChanged();
    partial void OnZoneChanging(string value);
    partial void OnZoneChanged();
    partial void OnPaycodeChanging(short value);
    partial void OnPaycodeChanged();
    partial void OnStartDateChanging(System.DateTime value);
    partial void OnStartDateChanged();
    partial void OnZoneCurrencyChanging(short value);
    partial void OnZoneCurrencyChanged();
    partial void OnMinAmountChanging(decimal value);
    partial void OnMinAmountChanged();
    partial void OnMidAmountChanging(decimal value);
    partial void OnMidAmountChanged();
    partial void OnMaxAmountChanging(decimal value);
    partial void OnMaxAmountChanged();
    partial void OnGradeZoneGUIDChanging(System.Guid value);
    partial void OnGradeZoneGUIDChanged();
    #endregion
		
		public GradeZone()
		{
			this._Grade1 = default(EntityRef<Grade>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grade", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short Grade
		{
			get
			{
				return this._Grade;
			}
			set
			{
				if ((this._Grade != value))
				{
					if (this._Grade1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGradeChanging(value);
					this.SendPropertyChanging();
					this._Grade = value;
					this.SendPropertyChanged("Grade");
					this.OnGradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zone", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Zone
		{
			get
			{
				return this._Zone;
			}
			set
			{
				if ((this._Zone != value))
				{
					this.OnZoneChanging(value);
					this.SendPropertyChanging();
					this._Zone = value;
					this.SendPropertyChanged("Zone");
					this.OnZoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paycode", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short Paycode
		{
			get
			{
				return this._Paycode;
			}
			set
			{
				if ((this._Paycode != value))
				{
					this.OnPaycodeChanging(value);
					this.SendPropertyChanging();
					this._Paycode = value;
					this.SendPropertyChanged("Paycode");
					this.OnPaycodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="SmallDateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZoneCurrency", DbType="SmallInt NOT NULL")]
		public short ZoneCurrency
		{
			get
			{
				return this._ZoneCurrency;
			}
			set
			{
				if ((this._ZoneCurrency != value))
				{
					this.OnZoneCurrencyChanging(value);
					this.SendPropertyChanging();
					this._ZoneCurrency = value;
					this.SendPropertyChanged("ZoneCurrency");
					this.OnZoneCurrencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinAmount", DbType="Decimal(18,3) NOT NULL")]
		public decimal MinAmount
		{
			get
			{
				return this._MinAmount;
			}
			set
			{
				if ((this._MinAmount != value))
				{
					this.OnMinAmountChanging(value);
					this.SendPropertyChanging();
					this._MinAmount = value;
					this.SendPropertyChanged("MinAmount");
					this.OnMinAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MidAmount", DbType="Decimal(18,3) NOT NULL")]
		public decimal MidAmount
		{
			get
			{
				return this._MidAmount;
			}
			set
			{
				if ((this._MidAmount != value))
				{
					this.OnMidAmountChanging(value);
					this.SendPropertyChanging();
					this._MidAmount = value;
					this.SendPropertyChanged("MidAmount");
					this.OnMidAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxAmount", DbType="Decimal(18,3) NOT NULL")]
		public decimal MaxAmount
		{
			get
			{
				return this._MaxAmount;
			}
			set
			{
				if ((this._MaxAmount != value))
				{
					this.OnMaxAmountChanging(value);
					this.SendPropertyChanging();
					this._MaxAmount = value;
					this.SendPropertyChanged("MaxAmount");
					this.OnMaxAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeZoneGUID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GradeZoneGUID
		{
			get
			{
				return this._GradeZoneGUID;
			}
			set
			{
				if ((this._GradeZoneGUID != value))
				{
					this.OnGradeZoneGUIDChanging(value);
					this.SendPropertyChanging();
					this._GradeZoneGUID = value;
					this.SendPropertyChanged("GradeZoneGUID");
					this.OnGradeZoneGUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Grade_GradeZone", Storage="_Grade1", ThisKey="Grade", OtherKey="Grade1", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Grade Grade1
		{
			get
			{
				return this._Grade1.Entity;
			}
			set
			{
				Grade previousValue = this._Grade1.Entity;
				if (((previousValue != value) 
							|| (this._Grade1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Grade1.Entity = null;
						previousValue.GradeZones.Remove(this);
					}
					this._Grade1.Entity = value;
					if ((value != null))
					{
						value.GradeZones.Add(this);
						this._Grade = value.Grade1;
					}
					else
					{
						this._Grade = default(short);
					}
					this.SendPropertyChanged("Grade1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
