//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string AName { get; set; }
        public int JobCatId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ChangeBy { get; set; }
        public System.DateTime ChageDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual JobCat JobCat { get; set; }
    }
}
