//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class t3
    {
        public long cust_id { get; set; }
        public long order_nbr { get; set; }
        public System.DateTime order_date { get; set; }
        public decimal order_amount { get; set; }
        public Nullable<decimal> runtot { get; set; }
        public Nullable<int> CHRONO_ORDER { get; set; }
    }
}
